### ISSUE TITLE
Poor document file name

### ISSUE THREAD

**Issue by ugurdogrusoz** [orhca/cs-oop-Group29#4]
Please change it and let me know.

**Comment by tbeihes** [comment]
I just uploaded the file with changed name. Sorry for inconvenience and delay.

**Comment by ugurdogrusoz** [comment]
Thanks but you should also remove the obsolete one.

**Comment by tbeihes** [comment]
Done.

**Comment by ugurdogrusoz** [comment]
@tbeihes always let the creator verify and close the issue!
